# Site Settings
title: GTM Setup Services
description: Emergency GTM recovery and comprehensive tracking audits. Fix broken Google Tag Manager in 2-4 hours.
url: https://gtmsetupservices.com
baseurl: ""

# SEO Settings
tagline: Fix Your GTM Tracking Issues Today
author:
  name: GTM Setup Services
  email: support@gtmsetupservices.com

# Jekyll Configuration
markdown: kramdown
permalink: /blog/:year/:month/:day/:title/

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

# Collections
collections:
  testimonials:
    output: false

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "GTM Setup Services"

# Analytics (to be configured)
google_analytics: # GA4 Measurement ID
gtm_container: # GTM Container ID

# CRM Settings
crm_endpoint: # Your FluentCRM API endpoint
crm_api_key: # Your FluentCRM API key

# Service-specific settings
service_type: gtm
emergency_price: "$397"
full_setup_price: "$797"
monitoring_price: "$197/month"